service: media-scraper

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

plugins:
  # - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 3000
    host: "0.0.0.0"

  webpack:
    webpackConfig: ./webpack.config.js
